### ISSUE TITLE
Scala 3 derivation of ConfigReader doesn't work with default values

### ISSUE THREAD

**Issue by sideeffffect** [pureconfig/pureconfig#1488]
```scala
import pureconfig._
import pureconfig.generic.derivation.default._

case class Person(name: String, age: Int = -1) derives ConfigReader

println(ConfigSource.string("{ name = foo }").load[Person])
```
prints
```scala
Left(ConfigReaderFailures(ConvertFailure(KeyNotFound(age,Set()),None,age)))
```

https://scastie.scala-lang.org/HdRYEUzCRme8LH4zffzlPQ

(Expected result is `Right(Person(foo,-1))`)

**Comment by ruippeixotog** [comment]
Fixed by #1636.

**Comment by bcarter97** [comment]
Is it possible to use this with `derives`?

As far as I can see you have to create a semiauto `deriveReader` for every case class, whereas before you could add `derives ConfigReader`. Is that the case or am i missing something?

**Comment by sideeffffect** [comment]
Nice, this works :tada: 
```scala
import pureconfig._
import pureconfig.generic.semiauto.*

case class Person(name: String, age: Int = -1)
object Person:
  given ConfigReader[Person] = deriveReader

println(ConfigSource.string("{ name = foo }").load[Person])

// Right(Person(foo,-1))
```
https://scastie.scala-lang.org/gqFJABbnQD6UnSl9I38NfQ

**Comment by sideeffffect** [comment]
But this still doesn't
```scala
import pureconfig.*
import pureconfig.generic.derivation.default.*

case class Person(name: String, age: Int = -1) derives ConfigReader

println(ConfigSource.string("{ name = foo }").load[Person])

// Left(ConfigReaderFailures(ConvertFailure(KeyNotFound(age,Set()),None,age)))
```
Not even with `"com.github.pureconfig" %% "pureconfig-generic-scala3" % "0.17.7"`
https://scastie.scala-lang.org/T3SR4at8Sy6IQfPLvfVr1g

I'll create a new ticket.
